language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cppcheck
 
before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make

